### ISSUE TITLE
Rename functions deprecated in WSAL 4.4.1

### ISSUE THREAD

**Issue by martinkrcho** [wpwhitesecurity/wsal-bbpress#49]
This is a follow-up ticket for changes made in version 4.4.1. We changed functions names to comply with WordPress coding standards in [this issue](https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/2451).

If the extension is using any of the following functions, we need to replace them with their snake case counterparts.
- `WpSecurityAuditLog::GetInstance`
- `WpSecurityAuditLog::SetGlobalBooleanSetting`
- `WpSecurityAuditLog::GetGlobalBooleanSetting`
- `WSAL_AlertManager::Trigger`
- `WSAL_AlertManager::TriggerIf`
- `WSAL_AlertManager::WillOrHasTriggered`
- `WSAL_AlertManager::WillTrigger`
- `WSAL_Models_OccurrenceQuery::addOrderBy`
- `WSAL_Models_OccurrenceQuery::setLimit`
- `WSAL_Models_OccurrenceQuery::getAdapter `
- `WSAL_Models_Occurrence::GetMetaArray`
- `WSAL_Adapters_QueryInterface::Execute`

We need to communicate very clearly that users need to update WSAL plugin to version 4.4.1 before updating the extension.

**Comment by robert81** [comment]
I do not know if this is the same as the issue we are having in 4.4.3, but just adding a note.

**Comment by DannyWPWS** [comment]
No warnings etc and the above has been taken care of so ill close this one up
